// test/SelfDual_test.m
print "Testing IsSelfOrthogonalZp and IsSelfDualZp...";

// Create simple test instance over Z_4 (p=2, s=2)
R := IntegerRing(4);
lengthSeq := [0, 2]; // alpha_1=0, alpha_2=2 (length 2 over Z_4)

// Simple self-dual code over Z_4 generated by (2,0) and (0,2)
G := Matrix(R, [[2, 0], [0, 2]]);
C := LinearCode(G);

assert IsSelfOrthogonalZp(C, lengthSeq) eq true;
assert IsSelfDualZp(C, lengthSeq) eq true;

print "SelfDual tests passed!";