// test/SelfDual_test.m
print "Testing IsSelfOrthogonalZp and IsSelfDualZp...";

// Create simple test instance over Z_4 (p=2, s=2)
R := IntegerRing(4);
lengthSeq := [0, 2]; // alpha_1=0, alpha_2=2 (length 2 over Z_4)

// Simple self-dual code over Z_4 generated by (2,0) and (0,2)
G := Matrix(R, [[2, 0], [0, 2]]);
C := LinearCode(G);

assert IsSelfOrthogonalZp(C, lengthSeq) eq true;
assert IsSelfDualZp(C, lengthSeq) eq true;

print "SelfDual tests passed!";

// Define the base ring Z_4
R := Integers(4);

// Define a block length sequence, e.g., alpha_1 = 0, alpha_2 = 2 (total length 2)
lengthSeq := [0, 2];

// Create two vectors over R of length 2
u := Vector(R, [1, 2]);
v := Vector(R, [2, 0]);