// test/SelfDual_test.m
print "Testing IsSelfOrthogonalZp and IsSelfDualZp...";

// Create simple test instance over Z_4 (p=2, s=2)
R := IntegerRing(4);
lengthSeq := [0, 2]; // alpha_1=0, alpha_2=2 (length 2 over Z_4)

// Simple self-dual code over Z_4 generated by (2,0) and (0,2)
G := Matrix(R, [[2, 0], [0, 2]]);
C := LinearCode(G);

// Wrap the linear code into a MixZpCode (p = 2, s = 2)
C_mix := MixZpAdditiveCode(C, 2, lengthSeq);

assert IsSelfOrthogonalZp(C_mix) eq true;
assert IsSelfDualZp(C_mix) eq true;

print "SelfDual tests passed!";

// Define the base ring Z_4
R := Integers(4);

// Define a block length sequence, e.g., alpha_1 = 0, alpha_2 = 2 (total length 2)
lengthSeq := [0, 2];

// Create two vectors over R of length 2
u := Vector(R, [1, 2]);
v := Vector(R, [2, 0]);

// Compute and print the mixed inner product
ip := MixZpInnerProduct(u, v, lengthSeq);
print "Mixed Inner Product:", ip;

// Create a code instance and test self-orthogonality/duality
G2 := Matrix(R, 1, 2, [2, 0]);
C2 := LinearCode(G2);

// Wrap this code instance into a MixZpCode as well
C2_mix := MixZpAdditiveCode(C2, 2, lengthSeq);

isOrthogonal := IsSelfOrthogonalZp(C2_mix);
print "Is self-orthogonal?", isOrthogonal;

isDual := IsSelfDualZp(C2_mix);
print "Is self-dual?", isDual;

// Testing over Z_8 (p = 2, s = 3)
R8 := Integers(8);
lengthSeq8 := [1, 1, 1]; // e.g., alpha_1 = 1, alpha_2 = 1, alpha_3 = 1

// Verify exponent sum condition: sum(i * alpha_i) should be even for self-dual codes
// 1(1) + 2(1) + 3(1) = 6 (which is even!)