{
  src
  {
    ZpAdditiveCodes_Core.m
    ZpAdditiveCodes_Constructions.m
    MixZpAdditiveCodes_Core.m
    MixZpInnerProduct.m
    SelfDualZp.m
    LinearBinaryCode.m
    MyPackage_Core.m
    MyNewFunction.m
}
